// Code generated by static/build_constants.go; DO NOT EDIT.

//go:generate go run ./static/build_constants.go

package clashy

var (
	// TroopBaseID is the base static-data ID offset for troops in army links.
	TroopBaseID = 4000000
	// SpellBaseID is the base static-data ID offset for spells in army links.
	SpellBaseID = 26000000
	// HeroBaseID is the base static-data ID offset for heroes in army links.
	HeroBaseID = 2000000
	// PetBaseID is the base static-data ID offset for pets in army links.
	PetBaseID = 60000000
	// EquipmentBaseID is the base static-data ID offset for hero equipment in army links.
	EquipmentBaseID = 30000000
	// ElixirTroopOrder lists regular home-village elixir troops in UI order.
	ElixirTroopOrder = []string{
		"Barbarian",
		"Archer",
		"Goblin",
		"Giant",
		"Wall Breaker",
		"Balloon",
		"Wizard",
		"Healer",
		"Dragon",
		"P.E.K.K.A",
		"Baby Dragon",
		"Miner",
		"Yeti",
		"Electro Dragon",
		"Dragon Rider",
		"Electro Titan",
		"Root Rider",
		"Thrower",
		"Meteor Golem",
	}
	// DarkElixirTroopOrder lists regular home-village dark elixir troops in UI order.
	DarkElixirTroopOrder = []string{
		"Minion",
		"Hog Rider",
		"Valkyrie",
		"Golem",
		"Witch",
		"Lava Hound",
		"Bowler",
		"Ice Golem",
		"Headhunter",
		"Apprentice Warden",
		"Ruin Witch",
		"Druid",
		"Furnace",
	}
	// HomeTroopOrder lists regular home-village troops in UI order.
	HomeTroopOrder = append(append([]string{}, ElixirTroopOrder...), DarkElixirTroopOrder...)
	// SiegeMachineOrder lists siege machines in UI order.
	SiegeMachineOrder = []string{
		"Wall Wrecker",
		"Battle Blimp",
		"Stone Slammer",
		"Siege Barracks",
		"Log Launcher",
		"Flame Flinger",
		"Battle Drill",
		"Troop Launcher",
		"Sky Wagon",
	}
	// SuperTroopOrder lists super troops in UI order.
	SuperTroopOrder = []string{
		"Super Barbarian",
		"Super Archer",
		"Super Wall Breaker",
		"Super Giant",
		"Sneaky Goblin",
		"Super Miner",
		"Rocket Balloon",
		"Inferno Dragon",
		"Super Valkyrie",
		"Super Witch",
		"Ice Hound",
		"Super Bowler",
		"Super Dragon",
		"Super Wizard",
		"Super Minion",
		"Super Hog Rider",
		"Super Yeti",
	}
	// HomeTroopOrderWithSieges lists regular home-village troops followed by siege machines.
	HomeTroopOrderWithSieges = append(append([]string{}, HomeTroopOrder...), SiegeMachineOrder...)
	// SeasonalTroopOrder lists temporary seasonal troops in static-data order.
	SeasonalTroopOrder = []string{
		"Ice Wizard",
		"Battle Ram",
		"Royal Ghost",
		"Pumpkin Barbarian",
		"Giant Skeleton",
		"Skeleton Barrel",
		"M.E.C.H.A",
		"Party Wizard",
		"Ram Rider",
		"Barcher",
		"Witch Golem",
		"Hog Wizard",
		"Lavaloon",
		"C.O.O.K.I.E",
		"Firecracker",
		"Azure Dragon",
		"Barbarian Kicker",
		"Giant Thrower",
		"Broom Witch",
		"Ice Minion",
		"Debt Collector",
		"Snake Barrel",
		"Giant Giant",
		"K.A.N.E",
		"The Disarmer",
		"YEETer",
		"Meteor Golem",
	}
	// BuilderTroopOrder lists Builder Base troops in UI order.
	BuilderTroopOrder = []string{
		"Raged Barbarian",
		"Sneaky Archer",
		"Beta Minion",
		"Boxer Giant",
		"Bomber",
		"Power P.E.K.K.A",
		"Cannon Cart",
		"Drop Ship",
		"Baby Dragon",
		"Night Witch",
		"Hog Glider",
		"Electrofire Wizard",
	}
	// ElixirSpellOrder lists regular elixir spells in UI order.
	ElixirSpellOrder = []string{
		"Lightning Spell",
		"Healing Spell",
		"Rage Spell",
		"Jump Spell",
		"Freeze Spell",
		"Clone Spell",
		"Invisibility Spell",
		"Recall Spell",
		"Revive Spell",
		"Totem Spell",
	}
	// DarkElixirSpellOrder lists regular dark elixir spells in UI order.
	DarkElixirSpellOrder = []string{
		"Poison Spell",
		"Earthquake Spell",
		"Haste Spell",
		"Skeleton Spell",
		"Bat Spell",
		"Overgrowth Spell",
		"Ice Block Spell",
		"Angry Spell",
	}
	// SeasonalSpellOrder lists temporary seasonal spells in static-data order.
	SeasonalSpellOrder = []string{
		"Santa's Surprise",
		"Bag of Frostmites",
	}
	// SpellOrder lists regular spells in UI order.
	SpellOrder = append(append([]string{}, ElixirSpellOrder...), DarkElixirSpellOrder...)
	// HomeBaseHeroOrder lists home-village heroes in unlock order.
	HomeBaseHeroOrder = []string{
		"Barbarian King",
		"Archer Queen",
		"Minion Prince",
		"Grand Warden",
		"Royal Champion",
		"Dragon Duke",
	}
	// BuilderBaseHeroOrder lists Builder Base heroes in unlock order.
	BuilderBaseHeroOrder = []string{
		"Battle Machine",
		"Battle Copter",
	}
	// HeroOrder lists all heroes in home-village then Builder Base order.
	HeroOrder = append(append([]string{}, HomeBaseHeroOrder...), BuilderBaseHeroOrder...)
	// PetOrder lists hero pets in unlock order.
	PetOrder = []string{
		"L.A.S.S.I",
		"Mighty Yak",
		"Electro Owl",
		"Unicorn",
		"Phoenix",
		"Poison Lizard",
		"Diggy",
		"Frosty",
		"Spirit Fox",
		"Angry Jelly",
		"Sneezy",
		"Greedy Raven",
	}
	// EquipmentOrder lists hero equipment in static-data order.
	EquipmentOrder = []string{
		"Barbarian Puppet",
		"Rage Vial",
		"Archer Puppet",
		"Invisibility Vial",
		"Eternal Tome",
		"Life Gem",
		"Seeking Shield",
		"Royal Gem",
		"Earthquake Boots",
		"Hog Rider Puppet",
		"Giant Gauntlet",
		"Vampstache",
		"Haste Vial",
		"Rocket Spear",
		"Spiky Ball",
		"Frozen Arrow",
		"Monolith Arrow",
		"Giant Arrow",
		"Heroic Torch",
		"Healer Puppet",
		"Fireball",
		"Rage Gem",
		"Snake Bracelet",
		"Healing Tome",
		"Dark Crown",
		"Magic Mirror",
		"Electro Boots",
		"Lavaloon Puppet",
		"Henchmen Puppet",
		"Dark Orb",
		"Metal Pants",
		"Noble Iron",
		"Action Figure",
		"Meteor Staff",
		"Frost Flake",
		"Stick Horse",
		"Fire Heart",
		"Rocket Backpack",
		"Stun Blaster",
		"Flame Blower",
		"Electro Fangs",
	}
	// HVBuildingOrder lists home-village buildings in static-data order.
	HVBuildingOrder = []string{
		"Army Camp",
		"Town Hall",
		"Elixir Collector",
		"Elixir Storage",
		"Gold Mine",
		"Gold Storage",
		"Barracks",
		"Laboratory",
		"Cannon",
		"Archer Tower",
		"Wall",
		"Wizard Tower",
		"Air Defense",
		"Mortar",
		"Clan Castle",
		"Builder's Hut",
		"Hidden Tesla",
		"Spell Factory",
		"X-Bow",
		"Dark Elixir Drill",
		"Dark Elixir Storage",
		"Dark Barracks",
		"Inferno Tower",
		"Air Sweeper",
		"Dark Spell Factory",
		"Eagle Artillery",
		"Bomb Tower",
		"Workshop",
		"B.O.B's Hut",
		"Scattershot",
		"Pet House",
		"Blacksmith",
		"Hero Hall",
		"Spell Tower",
		"Monolith",
		"Multi-Gear Tower",
		"Sour Elixir Cauldron",
		"Multi-Archer Tower",
		"Ricochet Cannon",
		"Revenge Tower",
		"Firespitter",
		"Helper Hut",
		"Crafting Station",
		"Super Wizard Tower",
	}
	// AchievementOrder lists achievements in village and UI-priority order.
	AchievementOrder = []string{
		"Keep Your Account Safe!",
		"Bigger & Better",
		"Discover New Troops",
		"Bigger Coffers",
		"Gold Grab",
		"Elixir Escapade",
		"Heroic Heist",
		"Well Seasoned",
		"Nice and Tidy",
		"Empire Builder",
		"Clan War Wealth",
		"Friend in Need",
		"Sharing is caring",
		"Siege Sharer",
		"War Hero",
		"War League Legend",
		"Games Champion",
		"Unbreakable",
		"Sweet Victory!",
		"Conqueror",
		"League All-Star",
		"League Follower",
		"League Enthusiast",
		"League Superfan",
		"League Fanatic",
		"League Master",
		"Humiliator",
		"Not So Easy This Time",
		"Union Buster",
		"Bust This!",
		"Wall Buster",
		"Mortar Mauler",
		"X-Bow Exterminator",
		"Firefighter",
		"Anti-Artillery",
		"Shattered and Scattered",
		"Counterspell",
		"Monolith Masher",
		"Multi-Archer Tower Terminator",
		"Ricochet Cannon Crusher",
		"Firespitter Finisher",
		"Multi-Gear Tower Trampler",
		"Crafter’s Nightmare",
		"Get those Goblins!",
		"Supercharger",
		"Crafting Connoisseur",
		"Get those other Goblins!",
		"Get even more Goblins!",
		"Dragon Slayer",
		"Ungrateful Child",
		"Superb Work",
		"Master Engineering",
		"Hidden Treasures",
		"High Gear",
		"Next Generation Model",
		"Un-Build It",
		"Champion Builder",
		"Aggressive Capitalism",
		"Most Valuable Clanmate",
	}
)
