//go:build ignore

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	clashy "github.com/clashkinginc/clashy.go"
)

type item map[string]any

func main() {
	ctx := context.Background()
	client, err := clashy.NewClient(clashy.DefaultClientConfig())
	if err != nil {
		fail(err)
	}
	if err := client.UpdateStatic(ctx); err != nil {
		fail(err)
	}
	data, err := os.ReadFile(filepath.Join("static", "static_data.json"))
	if err != nil {
		fail(err)
	}

	var staticData map[string][]item
	if err := json.Unmarshal(data, &staticData); err != nil {
		fail(err)
	}

	troops := staticData["troops"]
	spells := staticData["spells"]
	heroes := staticData["heroes"]
	pets := staticData["pets"]
	equipment := staticData["equipment"]
	buildings := staticData["buildings"]
	achievements := append([]item(nil), staticData["achievements"]...)

	homeHeroes := filter(heroes, func(h item) bool { return stringValue(h, "village") == "home" })
	sort.SliceStable(homeHeroes, func(i, j int) bool {
		return requiredTownhall(homeHeroes[i]) < requiredTownhall(homeHeroes[j])
	})
	sort.SliceStable(achievements, func(i, j int) bool {
		iv, jv := villageOrder(achievements[i]), villageOrder(achievements[j])
		if iv != jv {
			return iv < jv
		}
		return intValue(achievements[i], "ui_priority") > intValue(achievements[j], "ui_priority")
	})

	lists := []constantList{
		{"ElixirTroopOrder", names(filter(troops, func(t item) bool {
			return stringValue(t, "production_building") == "Barracks" && !boolValue(t, "is_seasonal") && !hasKey(t, "super_troop")
		}))},
		{"DarkElixirTroopOrder", names(filter(troops, func(t item) bool {
			return stringValue(t, "production_building") == "Dark Barracks" && !boolValue(t, "is_seasonal") && !hasKey(t, "super_troop")
		}))},
		{"HomeTroopOrder", "append(append([]string{}, ElixirTroopOrder...), DarkElixirTroopOrder...)"},
		{"SiegeMachineOrder", names(filter(troops, func(t item) bool { return stringValue(t, "production_building") == "Workshop" }))},
		{"SuperTroopOrder", names(filter(troops, func(t item) bool { return hasKey(t, "super_troop") }))},
		{"HomeTroopOrderWithSieges", "append(append([]string{}, HomeTroopOrder...), SiegeMachineOrder...)"},
		{"SeasonalTroopOrder", names(filter(troops, func(t item) bool { return boolValue(t, "is_seasonal") }))},
		{"BuilderTroopOrder", names(filter(troops, func(t item) bool { return stringValue(t, "village") == "builderBase" }))},
		{"ElixirSpellOrder", names(filter(spells, func(s item) bool {
			return stringValue(s, "upgrade_resource") == "Elixir" && !boolValue(s, "is_seasonal")
		}))},
		{"DarkElixirSpellOrder", names(filter(spells, func(s item) bool { return stringValue(s, "upgrade_resource") == "Dark Elixir" }))},
		{"SeasonalSpellOrder", names(filter(spells, func(s item) bool { return boolValue(s, "is_seasonal") }))},
		{"SpellOrder", "append(append([]string{}, ElixirSpellOrder...), DarkElixirSpellOrder...)"},
		{"HomeBaseHeroOrder", names(homeHeroes)},
		{"BuilderBaseHeroOrder", names(filter(heroes, func(h item) bool { return stringValue(h, "village") == "builderBase" }))},
		{"HeroOrder", "append(append([]string{}, HomeBaseHeroOrder...), BuilderBaseHeroOrder...)"},
		{"PetOrder", names(pets)},
		{"EquipmentOrder", names(equipment)},
		{"HVBuildingOrder", names(filter(buildings, func(b item) bool { return stringValue(b, "village") == "home" }))},
		{"AchievementOrder", names(achievements)},
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by static/build_constants.go; DO NOT EDIT.\n\n")
	out.WriteString("//go:generate go run ./static/build_constants.go\n\n")
	out.WriteString("package clashy\n\n")
	out.WriteString("var (\n")
	out.WriteString("\tTroopBaseID     = 4000000\n")
	out.WriteString("\tSpellBaseID     = 26000000\n")
	out.WriteString("\tHeroBaseID      = 2000000\n")
	out.WriteString("\tPetBaseID       = 60000000\n")
	out.WriteString("\tEquipmentBaseID = 30000000\n")
	for _, list := range lists {
		switch value := list.value.(type) {
		case string:
			fmt.Fprintf(&out, "\t%s = %s\n", list.name, value)
		case []string:
			fmt.Fprintf(&out, "\t%s = []string{\n", list.name)
			for _, name := range value {
				fmt.Fprintf(&out, "\t\t%q,\n", name)
			}
			out.WriteString("\t}\n")
		}
	}
	out.WriteString(")\n")

	if err := os.WriteFile("constants.go", out.Bytes(), 0o644); err != nil {
		fail(err)
	}
	fmt.Println("Constants written to constants.go")
}

type constantList struct {
	name  string
	value any
}

func filter(items []item, keep func(item) bool) []item {
	var out []item
	for _, item := range items {
		if keep(item) {
			out = append(out, item)
		}
	}
	return out
}

func names(items []item) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, stringValue(item, "name"))
	}
	return out
}

func hasKey(item item, key string) bool {
	_, ok := item[key]
	return ok
}

func stringValue(item item, key string) string {
	value, _ := item[key].(string)
	return value
}

func boolValue(item item, key string) bool {
	value, _ := item[key].(bool)
	return value
}

func intValue(item item, key string) int {
	value, _ := item[key].(float64)
	return int(value)
}

func requiredTownhall(hero item) int {
	levels, _ := hero["levels"].([]any)
	if len(levels) == 0 {
		return 0
	}
	first, _ := levels[0].(map[string]any)
	value, _ := first["required_townhall"].(float64)
	return int(value)
}

func villageOrder(item item) int {
	switch strings.ToLower(stringValue(item, "village")) {
	case "home":
		return 0
	case "builderbase":
		return 1
	case "clancapital":
		return 2
	default:
		return 0
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
